//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mohragan2019.Monastery.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int MonasteryID { get; set; }
        public string Image { get; set; }
        public string ImageDescription { get; set; }
        public string PlaceContent { get; set; }
    
        public virtual Monastery Monastery { get; set; }
    }
}
